### ISSUE TITLE
There are no tests

### ISSUE THREAD

**Issue by Fayti1703** [Fayti1703/BinaryMatrixPlayer#4]
All current testing was performed locally, using `BinaryMatrixEngineAccessor` in a terminal session. This does not scale, nor is it particularly exhaustive.

Adding some unit tests would allow for increased confidence that the code behaves correctly, particularly after changes to the internals.

### Dependencies
- [x] #3

**Comment by Fayti1703** [comment]
@samualtnorman, you have some tests over at [samualtnorman/binmat@`5e26d8d2`:test/](https://github.com/samualtnorman/binmat/tree/5e26d8d244e4d37669e94092fb0ad298fc3537e0/test); would you mind if I adapted these here?

**Comment by samualtnorman** [comment]
> @samualtnorman, you have some tests over at [samualtnorman/binmat@`5e26d8d2`:test/](https://github.com/samualtnorman/binmat/tree/5e26d8d244e4d37669e94092fb0ad298fc3537e0/test); would you mind if I adapted these here?

go ahead and use anything you need
